name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the repo! Thanks for submitting an issue, I'll make sure to have a look at it.'
        pr-message: 'Thanks for contributing to the repo'
